apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-rtmp-config
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }

    rtmp {
        server {
            listen 1935;
            chunk_size 4096;

            application live {
                live on;
                record off;
            }
        }
    }
